### ISSUE TITLE
How to get the image height and width property

### ISSUE THREAD

**Issue by VerzatileTom** [danialfarid/ng-file-upload#1059]
Hi, i want to display a warning that the uploaded image has reached beyond the required height and width but i want the uploading to continue. How can i get its height and width property?

**Comment by danialfarid** [comment]
You can use `Upload.imageDimensions(file)` in your js code.
Or you can specify `ngf-max-height/width` and then set `ng-model-options="{allowInvalid: true}", so that the invalid files would still be passed to model, and then you can get the width and height of the images with `file.$ngfWidth` and `file.$ngfHeight`.

**Comment by himanshuranavat** [comment]
dont see the method Upload.imageDimensions(file) anywhere.

**Comment by danialfarid** [comment]
It is in the readme file.

**Comment by VerzatileTom** [comment]
@danialfarid i saw that on doc. But i don't think i understand that clearly. But what you said is now very clear to me. Thanks!
