### ISSUE TITLE
ng-model is cleared whenever ngf-select element is opened again.

### ISSUE THREAD

**Issue by hachiwang** [danialfarid/ng-file-upload#1079]
Sample Jade file as below:
````
div(ngf-select ng-model="file")
  img(ngf-src="file" ngf-resize="{width: 60, height: 60}")
````
Step 1. I click this div and choose an image, then the preview of this image will be displayed in img element.
Step 2. I click the div again, the preview of previous image disappears immediately even if I cancel choosing this time. Is there any options here to keep the previous image until I choose another image.

Thanks

**Comment by hachiwang** [comment]
I noticed a similar issue: https://github.com/danialfarid/ng-file-upload/issues/1056, but it doesn't solve my problem. @danialfarid, is there a way to disable the default behavior by chrome or other browsers?

Thanks

**Comment by danialfarid** [comment]
You can add `ng-model-options="{updateOn: ''change drop paste'}"` but chrome browser by default resets the input if you click cancel on the popup, that's why I make it to reset the input on click to make it behave the same cross browser. The popup behaviour is browser dependent and I don't think there is a way to make chrome not to remove the file when you click cancel.

From the user perspective it should be ok, when they click on the browse again they wanted to select another file and if they change their mind they can select the same file again.

Other workaround would be to keep the file model in another model and whenever the file select is called with empty value set the file model to the previous file.

Maybe I can add an option to make every browser behave like firefox so if they cancel it would be noop.

**Comment by hachiwang** [comment]
Thanks for your suggestion. My workaround is similar by just watching the file model like follows:
````
$scope.$watch(name, function(newValue, oldValue){
	if(newValue) {
		$scope[name] = newValue;
	} else {
		$scope[name] = oldValue;
	}
});
````
