### ISSUE TITLE
show progress icon while resizing

### ISSUE THREAD

**Issue by robertfink** [danialfarid/ng-file-upload#1137]
On mobile devices the resizing of an image (ngf-resize: drawing to canvas) take a while (7-10 sec.). Now we would show a progress icon while resizing but couldn't find a working solutions.

Can anyone help us? Is there a simple solution?
Thanks!

**Comment by danialfarid** [comment]
Upgrade  to version 10.1.0
There is no progress callback, but you can show a throbber icon by using 'ngf-before-model-change="startResizing($files)"` and then when the ngf-select is called or model is changed it would be the end of resize.

**Comment by enure** [comment]
Thanks for the help @danialfarid.

**Comment by AdeelMufti** [comment]
Thanks. I was struggling with this for a while until I came across the ngf-before-model-change directive.

In case it isn't clear to anyone (it wasn't to me at first), this is how it works:

HTML:
            <div ngf-select="afterResizingImages($files)"
                 ngf-before-model-change="beforeResizingImages($files)"
                 ...

Controller:
    $scope.beforeResizingImages = function(images)
    {
      blockUI.start($translate.instant('FORMATTING_IMAGES')+"...");
      $scope.$apply();  //Not sure if this is necessary
    }
    $scope.afterResizingImages = function(images)
    {
      blockUI.stop();
    }

Of course I'm using the blockUI module to put a message up, and translating the message based on the user's language. You can do whatever you chose to let the user know images are being resized, otherwise the browser just hangs for a while and makes the user wonder what is going on.

**Comment by razblack** [comment]
This wasn't working so well for me until i enabled blockUIConfig.delay = 1; in my app config.
The default I believe is 100ms, and on very large PNG images, the promise was returning too quickly while the UI was still lagging.. unfortunately, during that the blockUI.start() was not firing, and I guess was getting cleared (or just not firing at all).
