### ISSUE TITLE
ng-required is not working with ng-if

### ISSUE THREAD

**Issue by bogdanalexe90** [danialfarid/ng-file-upload#1144]
Hi,
If i use the component with `ng-required` inside an `ng-if` when `ng-if` changes the model is not valid anymore. Take the following use case:

1. ng-if = true
2. select a file (required is valid)
3. ng-if = false
4. ng-if = true
5 required is invalid, if i change the file it becomes valid again.

**Comment by bogdanalexe90** [comment]
May be related to this one https://github.com/danialfarid/ng-file-upload/issues/1052

In my case the initial value is a valid File object. Because `ng-if` will destroy the directive but not the model. When the directive is re-created some how model is interpreted as invalid.

**Comment by bogdanalexe90** [comment]
After a bit of investigation i noticed that this will never work because a big part of the validation logic it was designed around that input[file] and there is no way to do 2way binding with it. Do you plan in the feature to refactor this around `ngModel` and to not stay tied to the native validation?

**Comment by danialfarid** [comment]
input file is kind of different from other inputs in the way that you cannot set a value for it programmatically, so there is no two way binding you can just set it to null.
I will have a look at it for the next release to see if it make sense to have the validation run on the model but not on the actual element's value.

**Comment by danialfarid** [comment]
Actually it is already tied to the model only. I am guessing when you have ng-if it would reset the model values that are bind to the newly compiled elements. If you could create a jsfiddle showing the issue I will investigate more.

**Comment by wickY26** [comment]
Hello, I design an editor where user needs to select a contentType from editor menu and each menu tab has its own validation rules depends on their content types.

So, some content types has file selector where I use your directive and its validations for it but when user select a content type and make it valid then move to another content type and turn back again valid nested form become invalid because of ng-if. 

I reproduced the error from your demos at home page. Here is the link for it http://jsfiddle.net/0rgm4az4/

For who looking for temporary solution you could use ng-show but then you need to put ng-show condition with ng-required for dynamic validation for invisible areas...

**Comment by danialfarid** [comment]
Fixed at 12.2.11
