### ISSUE TITLE
updating files from server

### ISSUE THREAD

**Issue by salimchami** [danialfarid/ng-file-upload#1204]
Hi! and thanks for this interesting directive.

I'm working on a form wich contains an upload part and when i submit my form, i save all the files in a server folder. 
After that, i want to display these files in a form to update it. How can use the same scope variables to store these files ? 

Now, i can retrieve my files from server (array of bytes) but i don't know how can i convert it to your directive variable "files". 

thanks

**Comment by danialfarid** [comment]
You don't need to put them back in the files variable. Just have a separate model like fileUrls and put the url of the uploaded files in there and to show them you can use:
`<img ngf-src="files[i] || fileUrls[i]">`
You cannot set the value of the file input programmatically because of the security reasons so even if you convert that byte array into a file object you cannot set it for the file input in the form.

**Comment by salimchami** [comment]
ok. Thank you. 
But my files aren't only img files. I have a lot of extensions. 
can i put a link (href) on each file to download it ?

**Comment by danialfarid** [comment]
If you don't care about form file input value being set you can do 
```
$http({url: url, method: 'get', responseType: 'arraybuffer'}).then(function (resp) {
            var arrayBufferView = new Uint8Array(resp.data);
            var type = resp.headers('content-type') || 'application/octet-stream';
            var blob = new window.Blob([arrayBufferView], {type: type});
            files.push(blob);
});
```

**Comment by salimchami** [comment]
Thanks a lot ! :+1:
