### ISSUE TITLE
ngf-pattern issue

### ISSUE THREAD

**Issue by suniltaneja** [danialfarid/ng-file-upload#1219]
Once an incorrect pattern is detected the form errors has a pattern error. How can this be cleaned out so the form can be submitted. The File upload is not mandatory.

**Comment by danialfarid** [comment]
remove the file and it will be cleared

**Comment by suniltaneja** [comment]
By clearing the file model, that seems to error out.

**Comment by danialfarid** [comment]
what error?

**Comment by Nitad** [comment]
I seem to have the same issue. If i select 3 photos and one is invalid, the model will show 2 files and the form will be set to invalid. How can i set the form to valid again?

**Comment by suniltaneja** [comment]
Exact issue. Tried a whole bunch of options set pristine, etc

**Comment by Nitad** [comment]
Ye, been at it for a few hours now. I'll keep fiddling with it and let you know if i can find a way around it.

**Comment by danialfarid** [comment]
If you could create a jsfiddle showing the issue I'll have a look.

**Comment by Nitad** [comment]
https://jsfiddle.net/2ge7r2an/6/

Say someone wants to upload some files. They select 3 files and 2 of them are valid, so the user should be able to just submit the 2 selected files instead of rendering the form unvalid and unable to proceed. I use the "validateImage" function to alert the user that one or more of the files they have selected is of an unvalid format, and ask them to continue or select other files. I only use the model as a temporary variable and after that push the files to another array. Hope it helps.

**Comment by danialfarid** [comment]
You can use `ng-model-options="{allowInvalid: true}"` to allow invalid files to

**Comment by Nitad** [comment]
But then i cannot alert the user that they have tried to upload an invalid file, right?

**Comment by danialfarid** [comment]
Fixed at version 10.1.13.
See: https://jsfiddle.net/2ge7r2an/11/
If you update the model value now it should revalidate the form.
Note that you need to change the array object. Calling splice on the array will not trigger angular model change so that's why I have `      	$scope.images = $scope.images.slice(0);`

**Comment by Nitad** [comment]
Sweet! Thanks for the quick fix!
