### ISSUE TITLE
Upload.urlToBlob(fileUrl) throw No 'Access-Control-Allow-Origin' header is present error...

### ISSUE THREAD

**Issue by hughred22** [danialfarid/ng-file-upload#1326]
So when I use Upload.urlToBlob(fileUrl), the browser throw error: 

XMLHttpRequest cannot load https://actorreels.stamplayapp.com/upload/cobject/originalphoto/1454468287536_Headshot-2.jpg. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://demoreel.com' is therefore not allowed access.

Could this function use JSONP to solve the different domain issue? Or how can I approach this?

**Comment by danialfarid** [comment]
Well if the url does not allow cross origin access I don't think there is much you can do. If you have access to origin server that provides the image you can allow cross origin access.

There might be some possible hacks I could look further to this but I think I did that before and there was no reliable easy way to get around this. Possibly you could load it in a canvas and then convert to image, but not sure if that would work.

**Comment by a-poptsov** [comment]
Maybe you can add ability to define backend proxy for urls?

**Comment by danialfarid** [comment]
This plugin is for front-end angular js. Backend code could be in any language technology so it depends on the server side code.

**Comment by schmkr** [comment]
Hey @danialfarid, I'm running into this issue now as well and. 
Your suggestion to configure a server correctly, is not a solution to this issue: You have no control whatsoever where users drop their files from. For example, a user can simply have one browser tab open with an image on it, start dragging that image and open the tab with the ng-file-upload app. When dropped, then the app tries to do an XHR from the url of the dropped image, but failing because of missing CORS-headers.

I think it would be very beneficial if you can configure the behavior of dropped (and pasted) files, to do nothing if there are no files in the event's dataTransfer property, that we don't want to try to extract files from html.

Any change you could reconsider this issue and see if configuring such a thing is possible? There are already [some checks before trying to extract files from html](https://github.com/danialfarid/ng-file-upload/blob/master/src/drop.js#L166), maybe add a check if extracting files from html is configured as disabled?

Many thanks in advance!
