### ISSUE TITLE
ngf-select function called with null

### ISSUE THREAD

**Issue by kikar** [danialfarid/ng-file-upload#1339]
Hi,
I think there is a problem with the function `ngf-select="uploadFile($file)"` following these steps:
1. Click to select a file
2. Click to select another file

When clicking the second time, the function `uploadFile` is called with $file = null.
Fiddle of the issue https://jsfiddle.net/kikar/25qnends/

**Comment by danialfarid** [comment]
That's expected, there are plenty of similar issues

**Comment by fbarbat** [comment]
I would expect the value to be not null too. Why is passing null an intended behavior? Which issue duplicates this one? Thanks.

**Comment by danialfarid** [comment]
Ok it wasn't the same issue, but the file might be rejected which in that case would be in error files. So check both of them

**Comment by fbarbat** [comment]
Will be this issue reopened then? Thanks!

**Comment by danialfarid** [comment]
As I said it is not an issue. The rejected files will be in error files. So you get all the selected files in either of files or error files.

**Comment by fbarbat** [comment]
I tried this issue's fiddle and it works different to my application. This fiddle (ng-file-upload version 11.2.3) returns file, null and then file again. In my application (ng-file-upload version 7.3.9) it just return file and then null. The last file never comes. 

Now I understand why you say it works. By design clients must to allow nulls to be received when these cases happen (for example, when the button is clicked a second time or errors). I can't upgrade right now so I will have to implement a workaround. Thanks!

**Comment by danialfarid** [comment]
You might already know but you can get the rejected files by ngf-model-invalid or ngf-select="select($invalidFiles, $files)". The files that won't pass the validation won't be set to model or $files.
