### ISSUE TITLE
Possible to apply exif rotation with thumbnail/preview image?

### ISSUE THREAD

**Issue by alexstanbury** [danialfarid/ng-file-upload#1434]
I can see no way to do this in the API, are there any plans to add it in the future?

**Comment by sandronm** [comment]
Hello Alex,
I was wondering exactly the same because the parameter "ngf-fix-orientation='boolean'" was not clear for me: I was thinking that the parameter will be applied to the uploaded picture. 

**In fact, this parameter is used to display the thumbnail or preview image.**
And yes it works!

See this ticket for complete history [#745](https://github.com/danialfarid/ng-file-upload/issues/745)
See this JSFiddle forked from the basic example with ngf-fix-orientation = "true":
[JSFiddle](http://jsfiddle.net/vm0bp7jx/1/)
