### ISSUE TITLE
File parameter null with ngf-max-size

### ISSUE THREAD

**Issue by fvidal1977** [danialfarid/ng-file-upload#1483]
This is my html code:
ngf-select ngf-change=setCedula($file) name="file" ngf-pattern="'image/*'" accept="image/*" ngf-max-size="2MB" ngf-resize="{width: 200, height: 200}"

My js

$scope.setCedula = function (file){	
		 if (file && file.$error != null){
			 $scope.cedulaSizeError=true;
		 }
		 else {$scope.file=file;
		 	$scope.reload=true;
		 }
	 };

If the file I select is bigger than 2MB, the file parameter is always null, so I'm not getting the file.$error. 
This is also happening in your demo page: https://angular-file-upload.appspot.com/

ngf-validate: 
{size: {max: '2MB', min: '10B'},  ...... ==== Select something bigger that 2MB, nothing happens.

I read in other post (https://github.com/danialfarid/ng-file-upload/issues/703) that I should use ($files, $rejectedFiles)

But I dont realize how to use that.
Please advice, thanks.

**Comment by danialfarid** [comment]
Read the docs and jsfiddle samples. Use 'ngf-model-invelid'.

**Comment by indiesquidge** [comment]
@fvidal1977, where you able to get `ngf-max-size` working properly? I am running into the same issue with the file coming into the controller function as `null`.

@danialfarid, I am not sure I understand what you mean by "Use `ngf-model-invalid`". [Grepping the project](https://github.com/danialfarid/ng-file-upload/search?utf8=%E2%9C%93&q=ngf-model-invalid) for `ngf-model-invalid` did not make things clearer for me. I expected to do something along the lines of
```html
<button
    ngf-select="vm.upload($file)" ngf-max-size="20MB" ngf-model="$file" ngf-model-invalid="invalidFiles"
    type="button">
    Upload
</button>
```
And then handle the error in the `upload` method, but `$file` is always returned as `null` if the upload is larger than the specified `ngf-max-size`. How can I get the proper error to show up so that I can display it to the user?

**Comment by ashleyconnor** [comment]
It's pretty easy. Bind `ngf-model-invalid="invalidFiles"` in your directive like you have done and then pass in the bound model to your controller:

```
<button
    ngf-select="vm.upload($file, invalidFiles)" ngf-max-size="20MB" ngf-model="$file" ngf-model-invalid="invalidFiles"
    type="button">
    Upload
</button>
```

Then you can check for any errors in your controller.

The alternative way is don't even add `ngf-max-size="20MB"` and just do the validation in the controller method - you have access to the file size there.

**Comment by danialfarid** [comment]
@indiesquidge create a jsfiddle explaining what you expect. It is hard to tell what is wrong without your code.
