### ISSUE TITLE
ngf-accept does not work

### ISSUE THREAD

**Issue by luco** [danialfarid/ng-file-upload#1558]
When I specify ngf-accept="'image/*'" on Android, it pops up a menu with camera,  camera recorder, audio recorder and documents while a default input file just gives me Camera and Documents.

**Comment by danielo515** [comment]
In my case (version 12.0.4) ngf-accept does not work at all. If I use just `accept`, it works as expected, but if I use `ngf-accept` I get an error on the console about not being able to read attr of undefined

```
angular.js:13424 TypeError: Cannot read property 'attr' of undefined
    at ng-file-upload.min.js:2
```

Looks like I'm using a version that relies on plain accept and where ngf-accept is not implemented. This is weird because I'm using the latest version available according to github.

Regards

**Comment by danialfarid** [comment]
Can you create a jsfiddle with steps to reproduce?
