### ISSUE TITLE
Canceling the file selection dialog should not reset the model

### ISSUE THREAD

**Issue by mmmichl** [danialfarid/ng-file-upload#1647]
Current behavior is to clear the ng-model if the the "select button" is clicked. This seems to be intended and [is a generalization of the chrome behavior](https://github.com/danialfarid/ng-file-upload/issues/1056#issuecomment-148109523).

Actually this behavior is something what I (and others #1373, #1079, #1056) did not expect and I too think, this is not a behavior a user is expecting. Therefore I build a workaround with the option `ngf-keep="'distinct'"` and adapted my functionality use the last array entry of the model.

It would be great if this functionality could be build in to the widget. :)

**Comment by luco** [comment]
@mmmichl 
`ng-model-options="{updateOn: 'change'}"`

**Comment by mmmichl** [comment]
@luco 
tried this along with the mentioned in the tickets menthoed `ng-model-options="{updateOn:'select drop dropUrl'}"`

see http://codepen.io/anon/pen/grkVzp/
when you select a file, the model is not updated on either ways..

**Comment by danialfarid** [comment]
`ng-model-options` is broken for angular version >= 1.3.
A fix is coming soon just to rename it to ngf-model-options and that would be the way to disable reset on click.

**Comment by danialfarid** [comment]
Since version 12.1.0 you can use `ngf-model-options="{updateOn: 'change'}"`

**Comment by mmmichl** [comment]
@danialfarid thank you for your quick response and whip out a fix so fast. :)
In Firefox canceling the dialog works fine now, but in Chrome still not. I updated my example http://codepen.io/anon/pen/grkVzp/

As you mentioned in the other tickets, this is by design (https://bugs.chromium.org/p/chromium/issues/detail?id=2508), but I would love to see an uniform behavior across the browser. If you need help, let me know.

**Comment by danialfarid** [comment]
It is not possible since Chrome is sending a change event when you close the dialog and reset the input type file value to null so the file will be gone after you close the popup. That's the main reason I made it by default to remove the old file after cancelling and in you follow the discussions earlier on this module more people were expecting this to happen and this would also allow uploading the same file again in case you want to upload twice or the first upload fails. I would rethink the design you have or make a separate area for showing the file selected.
