### ISSUE TITLE
Add A FileReader Shim

### ISSUE THREAD

**Issue by opticyclic** [danialfarid/ng-file-upload#1682]
It would be useful if you added a FileReader shim for lower versions of IE and an api layer that made uploading a file without a server a simple process.

**Comment by danialfarid** [comment]
Some of the methods are already available in the shim using the FileAPI but not all and with some limitations on the file size. You can check out the shim file source code to see which methods are implemented. Since this is just to support dying browsers unless you are willing to contribute it won't get enough time hence closing this.
