### ISSUE TITLE
Be able to upload big file using $upload.http

### ISSUE THREAD

**Issue by killfill** [danialfarid/ng-file-upload#179]
In reference to issue #88, It would be nice to be able to upload big files (>500MB) using the .http() method.

When i try to upload big files (i.e. 500MB), the browser crashed. I can see FileRead is reading the whole file, when finished, triggers the onload event where $upload.http() is been called. Its crashing there.

Would be nice to ablt to stream the file to the server.

Thanks!!

**Comment by Dr-Steve** [comment]
I hit this issue too, I could not upload files over about 100MB.  My standard use case was 200MB files, so this was naturally frustrating.  After a few days of testing different things, I found that it was using filer reader https://developer.mozilla.org/en-US/docs/Web/API/FileReader

Apparently filereader crashes in chrome only on files greater than about 100 MB.  There were a few old bug reports about it on the goolge lists, but no one seemed to care enough to fix it.

My workaround was to not use filereader but instead directly reference the input DOM element (note that I use that content type because I am using pre-signed urls to amazon S3.  You may need a different content type.  Same with PUT vs POST):

var myFile = document.getElementById('file_to_upload');

$scope.upload = $upload.http({
          method: 'PUT',
          url: (your URL here),
          data: myFile.files[0],
          headers: {'Content-Type': ' '},
          transformRequest: []
        }).then(function() { ...


Hopefully this helps someone else out there, it took me days to figure out despite it being a relatively simple fix.  I thought that the issue was .http not supporting this size files but it was filereader.

**Comment by abodacs** [comment]
+1

**Comment by danialfarid** [comment]
It is fixed in version 3.3.4

**Comment by renan-sugiyama** [comment]
@Dr-Steve thanks so much!!!!!!!
