### ISSUE TITLE
Bits instead of bytes in sample

### ISSUE THREAD

**Issue by stibay** [danialfarid/ng-file-upload#1795]
Minor issue in the **Upload with form submit and validations** sample http://jsfiddle.net/danialfarid/maqbzv15/1118/ where it shows the size of the file (if it's too big) in bits instead of bytes. 
```
<i ng-show="myForm.file.$error.maxSize">File too large 
          {{errorFile.size / 1000000|number:1}}MB: max 2M</i>
```
Have to do  `{{errorFile.size / 1024 / 1024|number:1}}` to get the correct size in MB :)

**Comment by jimmywarting** [comment]
Actually, it's correct... https://en.wikipedia.org/wiki/Mebibyte

1 MB = 1000000 byte
1 MiB = 1048576 bytes

**Comment by stibay** [comment]
What? The symbol for mebibyte is MiB... the errorFile.size is clearly in bytes so if you actually want to write MB (megabyte) you have to divide it by 1024 / 1024

**Comment by jimmywarting** [comment]
First, there are two types of prefix when talking about digital information (read *bytes*): **SI prefixes** and **binary prefixes**.

## SI prefixes

SI prefixes are powers of 1,000 (1,000<sup>1</sup>, 1,000<sup>2</sup>, 1,000<sup>3</sup>, etc.):

 * 1 kB = 1 kilobyte = 1,000<sup>1</sup> bytes = 1,000 bytes;
 * 1 MB = 1 megabyte = 1,000<sup>2</sup> bytes = 1,000,000 bytes;
 * 1 GB = 1 gigabyte = 1,000<sup>3</sup> bytes = 1,000,000,000 bytes;
 * and [so on](http://en.wikipedia.org/wiki/SI_prefix#List_of_SI_prefixes).

As you can see, only SI symbols *mega* and above are capitalized.

## Binary prefixes

Binary prefixes are powers of 1,024 (1,024<sup>1</sup>, 1,024<sup>2</sup>, 1,024<sup>3</sup>, etc.):

 * 1 KiB = 1 kibibyte = 1,024<sup>1</sup> bytes = 1,024 bytes;
 * 1 MiB = 1 mebibyte = 1,024<sup>2</sup> bytes = 1,048,576 bytes;
 * 1 GiB = 1 gibibyte = 1,024<sup>3</sup> bytes = 1,073,741,824 bytes;
 * and [so on](http://en.wikipedia.org/wiki/Binary_prefix#Specific_units_of_IEC_60027-2_A.2_and_ISO.2FIEC_80000).

As you can see here, every binary symbol is capitalized and an lower-case *i* is added before the *B* symbol to indicate that we are talking about kibibytes instead of kilobytes, mebibytes instead of megabytes, etc.

**Comment by jimmywarting** [comment]
The word **Kilo** (from the Greek χίλιοι) means one thousand (1000)
