### ISSUE TITLE
$scope.upload progress/success callbacks not working

### ISSUE THREAD

**Issue by leaky** [danialfarid/ng-file-upload#224]
I have the angular-file-upload script and it's posting to my express app which is then saving the file, so the good news is that the script is working... However, for some reason the progress/success callbacks don't seem to be doing anything at all and my developer console just remains blank...?

```
$scope.onFileSelect = function ($files) {
                var file = $files;
                $scope.upload = $upload.upload({
                    url: '/upload',
                    data: {myObj: $scope.myModelObj},
                    file: file
                }).progress(function (evt) {
                    console.log('percent: ' + parseInt(100.0 * evt.loaded / evt.total));
                }).success(function(data, status, headers, config) {
                    console.log(data);
                });
        };
```

**Comment by justgeek** [comment]
have same issue , progress function is never called , only the promise success , and error functions are invoked right.

**Comment by sita1** [comment]
in my case progress and success working on local machine but success not working when connect to server

**Comment by diogomunhos** [comment]
Same here, progress function is never called

**Comment by raphibolliger** [comment]
I have the same problem.
Maybe its a serverside problem? I use the new ASP.NET Core MVC Framework.

**Comment by dwasyluk** [comment]
I'm having this issue as well, callbacks (particularly in Firefox) are not being called. If I remove the "progress" callback and leave only the success handler it starts working again in FF, but I need to maintain progress. In the code below, the .then() for success is never reached in Firefox. If I remove the .progress() function such that there is only a .then() it seems to start working in FF (without progress).

` attachmentService.uploadAttachment($files[i]).progress(function(evt) {
              percentUploaded = parseInt((100.0 * evt.loaded / evt.total).toString(), 10);
            }).then(function(res) {
              if (res && res.data && res.data.attachmentResponse) {
                attachments[index].link = res.data.attachmentResponse.link;
                delete attachments[index].percentUploaded;
              }
            }, function(res) { // something went wrong 
                 console.log("something went wrong with upload");
              }
            });`

I'm using ng-file-upload 12.2.12, Typescript (ES6) and webpack. I'm loading ng-file-upload from npm, and it looks like ng-file-upload-all already includes the shim as needed, what am I doing wrong? Because im using ES6 modules its highly likely that angular is getting loaded _before_ the shim/ng-file-upload, do I need to force the loading of ng-file-upload before angular? or just the shim needs to load before angular?

**Comment by phidang** [comment]
I'm having the same problem. Anyone fixed this?

**Comment by frguthmann** [comment]
Same problem here still today, shim imported before angular. I have the success callback called but not the progress. I'm wondering if my server is doing something wrong too.
