### ISSUE TITLE
Sync files using angular file upload

### ISSUE THREAD

**Issue by pavei** [danialfarid/ng-file-upload#332]
I have an app that's save photos and videos offline. How can i do the upload when the internet connection is active?
When i save offline file, i don't have a $file instance.

**Comment by tangervu** [comment]
@danialfarid @pavei how should we monitor if the connection is up? navigator.onLine is not supported by all browsers plus the connection can be lost during the file transfer. This can be a major issue on sites designed for mobile use.

I have been trying to create a file upload buffer that would simply try again until the file upload is successful, see https://gist.github.com/tangervu/b6bed70c952b865966d8. The solution works with $http upload but with $upload it just causes a lot of errors. Any ideas why my code doesn't work with $upload?

Tested with version 2.0.5.

**Comment by danialfarid** [comment]
@tangervu I don't exactly get what you are trying to do and what data are you sending to the server but this approach probably is not gonna work cause of encoding of the data and you need specific code on the server side to put the pieces together to the file.

If you are just posting a simple string to the server you don't need to use this plugin.

**Comment by tangervu** [comment]
@danialfarid I use this plugin on a site where user submits images using a mobile device. The problem is that on mobile devices the network connection to the backend server will be down occasionally but the user should be all the time able to continue taking pictures an putting those on queue for uploading them to the backend server when the connection is again working.

My approach to solve this issue was to try to send the data again and again until the backend server has recieved the complete file. As I tested the code linked above I noticed that this plugin itself creates a lot of errors when the server can't be reached and it somehow messes up the data that was being uploaded so that a new try is not anymore possible (unlike when using $http).

What would be the correct way to detect transfer errors for this plugin?
