### ISSUE TITLE
Issue with grunt build

### ISSUE THREAD

**Issue by lightshire** [danialfarid/ng-file-upload#385]
There's an issue regarding `grunt serve:dist` or `grunt build` I'm currently having issues with the module stating that

```
Uncaught Error: [$injector:modulerr] Failed to instantiate module userDashboardApp due to:
Error: [$injector:modulerr] Failed to instantiate module angularFileUpload due to:
Error: [$injector:nomod] Module 'angularFileUpload' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
```

Can't run the whole app

**Comment by iscoolapp** [comment]
Hi @danialfarid I'm facing the same problem. Is there anything that I could do?

**Comment by danialfarid** [comment]
Create a new jira with details of your issue, libraries versions code, etc.

**Comment by oaibr** [comment]
Uncaught Error: [$injector:modulerr] Failed to instantiate module userDashboardApp due to:
Error: [$injector:modulerr] Failed to instantiate module angularFileUpload due to:
Error: [$injector:nomod] Module 'ngFileUpload' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.


Hi @danialfarid I'm facing the above problem when doing grunt build. 

I have included "ng-file-upload":"latest" in my bower json.
