### ISSUE TITLE
Disable File Drop Based on State of Scope

### ISSUE THREAD

**Issue by lancecaraccioli** [danialfarid/ng-file-upload#611]
Need to add an attribute which allows the calling context to disable the file drop based on the state of the calling scope.

**Comment by danialfarid** [comment]
Why don't you use `ng-disable` which should be already working?

**Comment by SimeonC** [comment]
ng-disabled doesn't seem to work for me, I've got an `<div ng-file-drop ng-file-select>` defined instance with an ng-repeat, the disabled value is changed correctly but drop events send through to the ng-file-change event and when I click on the element I get the file popup.

See fiddle here: http://jsfiddle.net/rdkbkej3/ - I just forked the fiddle off the readme and added ng-disabled to everything.

**Comment by danialfarid** [comment]
Yep that's a bug

**Comment by danialfarid** [comment]
This should be fixed in version 3.2.0

**Comment by lancecaraccioli** [comment]
i need to disable all functionality, meaning dragenter and dragleave class
changes need to not happen in some states.


Lance Caraccioli, Senior Front End Engineer, Elance-oDesk

*blog*http://lance.caraccioli.me/*resume*http://lance.caraccioli.me/resume
*github*https://github.com/lancecaraccioli*linkedin*
http://www.linkedin.com/in/lancecaraccioli*elance*
https://www.elance.com/s/lancecaraccioli/*smarterer*
http://smarterer.com/lancecaraccioli*pastebin*
http://pastebin.com/u/LanceCaraccioli*email*lance.caraccioli@gmail.com*cell*(225)
328-6236

**Comment by lancecaraccioli** [comment]
also ng-disable is designed for input elements only correct?  I don't believe this would work for div elements with the ng-file-drop directive applied.

**Comment by lancecaraccioli** [comment]
nm I see that you made the changes to master.  next time please ask me to change the PR so I can get contribution credit.

**Comment by danialfarid** [comment]
For the future try to keep your changes to minimum and you just need to change demo/war/js/angular-file-upload.js, the grunt script will take care of changing the version and creating the -all scripts.
I do welcome contribution, but I would avoid lots of back and forth to get a PR automatically merged. So if the changes are minimal and is discussed beforehand I would merge automatically but if I am in the middle of changing other stuff and that could cause conflicts I would merge it manually.
For example for this PR there was no need to change the version or all scripts and the attribute name shoul've been changed to ng-disabled and there was no need to mention in readme file since it is standard angular directive.

**Comment by danialfarid** [comment]
Anyway thanks for opening the issue and submitting the PR.

**Comment by lancecaraccioli** [comment]
Hey man, thanks for the feedback.  I'll keep it simple on the next one.  Definitely agree with using ng-disable, though I think I'd still want to mention it in usage docs, as it's intuitive, but not necessarily obvious.

**Comment by SimeonC** [comment]
I've grabbed the new version and ng-disabled works correctly now, just thought I'd confirm that here.

**Comment by inukshuk** [comment]
I noticed this seems to have been changed to `ngf-disabled` [here](https://github.com/danialfarid/ng-file-upload/blob/master/demo/war/js/ng-file-upload.js#L349) -- was that changed on purpose or is it a typo? If changed to the ngf prefix I'd suggest to add the option to the Readme.

**Comment by danialfarid** [comment]
Fixed in version 4.2.0.
It should be ng-disabled.
