### ISSUE TITLE
selenium support

### ISSUE THREAD

**Issue by KhodeN** [danialfarid/ng-file-upload#650]
Need ability to select file without open dialog (for selenium tests).
Usually, selenium send keys (file path) to `<input type="file">`, then submits form.

```java
WebElement upload = driver.findElement(By.id("myfile"));
upload.sendKeys("/Users/sso/the/local/path/to/darkbulb.jpg");
driver.findElement(By.id("submit")).click();
```
How can I do this with `ng-file-upload`? `input` elements not exists until click :-(.

**Comment by joshribakoff** [comment]
@KhodeN This directive did work in Selenium if you revert to 3.1

I actually had a ton of Protractor tests that use this directive. On Friday, they suddenly started failing. After spending dozens of man hours, our team finally found this in Intellij's local history:

![selection_238](https://cloud.githubusercontent.com/assets/4021306/6919176/94ee019a-d769-11e4-803e-a94859db0304.png)

Someone must have added an unrelated bower dependency to our project, which changed the logic on which version of this directive got checked out. It appears that somewhere between 3.1 & 3.2, Selenium support was broken.

I also typed up  a stack overflow post that I never actually submitted, while I was debugging. I still have the tab open & I'll paste it here in case it helps anyone debug:

We had a Protractor test that uses `sendKeys` to type filename in to a `<input type="file">`. The test has been successfully uploading files for months. Today it stopped working.

        $('input[type="file"]').sendKeys(absolutePath);
        browser.actions().sendKeys(protractor.Key.ENTER).perform();

Today we noticed that this test began failing. We have reverted our code & all dependencies (composer, bower, npm) back to where we knew it was working. The tests still fail.

This lead us to believe the issue was a regression in Chrome, webdriver, selenium or Protractor itself. One by one we reverted each of these & the tests still fail.

In order to debug, I've setup a page called `test.html` that contains nothing but the upload directive. I've output the value of the `ng-model` for the upload directive as json. I also set the text of a `<div>` to "changed", and log an error to the console saying "got here".

**Here is what I see when I select a file manually:**
![enter image description here][1]


**Here is what I see when Protractor selects the file (used to work):**
![enter image description here][2]


As you can see, it appears the value of the input was set. I can also bind to it via jquery & confirm the `change` event is firing:

    jQuery(document).on('ready', function() {
        jQuery('input[type="file"]').on('change', function () {
            console.error('yay!');
        });
    });

I'm then observing the console errors in my test like this:

    browser.manage().logs().get('browser').then(function(browserLog) {
            console.log('\n log: ' + require('util').inspect(browserLog));
        });

I see this output to my terminal when running the tests, which seems to indicate the `change` event of my `input` is indeed firing correctly:
![enter image description here][3]


  [1]: http://i.stack.imgur.com/3llwR.png
  [2]: http://i.stack.imgur.com/tXJMa.png
  [3]: http://i.stack.imgur.com/3GPer.png

##test-spec.js##:
```js
var path = require('path');

describe('test', function() {

    // wait for angular
    beforeEach(function() {
        browser.ignoreSynchronization = false;
    });

    it('test', function() {
        browser.get('/test.html');
        var fileToUpload = 'fixtures/slide1.png';
        var absolutePath = path.resolve(__dirname, fileToUpload);
        $('input[type="file"]').sendKeys(absolutePath);
        browser.actions().sendKeys(protractor.Key.ENTER).perform();
        

        expect(element(by.css('#myLog')).getText()).toEqual('changed');

        browser.manage().logs().get('browser').then(function(browserLog) {
            console.log('\n log: ' + require('util').inspect(browserLog));
        });

        browser.pause();
    });

});
```

##test.html##:
```js
<!DOCTYPE html>
<html lang="en">
<head>
    <script src="https://code.jquery.com/jquery-1.11.2.js"></script>
    <script src="/vendor/angular/angular.js"></script>
    <script src="/vendor/ng-file-upload/angular-file-upload-all.js"></script>
</head>
<body ng-app="fileUpload" ng-controller="MyCtrl">

<pre>{{files|json}}</pre>
<input type="file" ng-file-select ng-model="files" name="file" accept="image/*" required>

<button ng-click="uploadPic(picFile)">Submit</button>


<div id="myLog"></div>

<script>

    jQuery(document).on('ready', function() {
        jQuery('input[type="file"]').on('change', function () {
            console.error('yay!');
        });
    });

    var app = angular.module('fileUpload', [ 'ngFileUpload' ]);
    var version = '3.2.4';

    app.controller('MyCtrl', [ '$scope', '$http', '$timeout', '$compile', '$upload', function($scope, $http, $timeout, $compile, $upload) {

        $scope.changeAngularVersion = function() {
            window.location.hash = $scope.angularVersion;
            window.location.reload(true);
        };

        $scope.angularVersion = window.location.hash.length > 1 ? (window.location.hash.indexOf('/') === 1 ?
                window.location.hash.substring(2): window.location.hash.substring(1)) : '1.2.20';

        $scope.$watch('files', function(files) {
            if(undefined !== files) {
                $scope.upload(files);
            }
        });

        $scope.upload = function (files) {
            jQuery('#myLog').html('changed');
            if (files && files.length) {
                for (var i = 0; i < files.length; i++) {
                    var file = files[i];
                    $upload.upload({
                        url: 'upload/url',
                        fields: {'username': $scope.username},
                        file: file
                    }).progress(function (evt) {
                        var progressPercentage = parseInt(100.0 * evt.loaded / evt.total);
                        console.log('progress: ' + progressPercentage + '% ' + evt.config.file.name);
                    }).success(function (data, status, headers, config) {
                        console.log('file ' + config.file.name + 'uploaded. Response: ' + data);
                    });
                }
            }
        };



    } ]);
</script>
</body>
</html>
```

**Comment by KhodeN** [comment]
I take my hat off to you) Big thx.

**Comment by KhodeN** [comment]
3.1.2 has bug - do not work correctly with accept="{{ ctrl.accept }}" attribute (with dynamic value). Rollback to 3.0.7.
Thanks for help and detailed explanation.

**Comment by danialfarid** [comment]
From version 3.2.x a new file input element will be created and clicked on when you click on the file upload element. So the change event is firing on the newly created element.

**Comment by KhodeN** [comment]
Yes, I read source. But this behavior is not compatible with Protractor or webdriver (selenium). How can I write e2e test for your control?

**Comment by joshribakoff** [comment]
I'd also imagine that breaks other things besides just Protractor. Probably older & mobile browsers, screen readers, maybe other libraries that expect events to work, etc...

**Comment by danialfarid** [comment]
Do you get the same result for input type file element and div?

**Comment by danialfarid** [comment]
When you click on the ng-file-select element, if it is file input, it would replace it with a new file input element and would click on the new element. If it is a div or button element it would insert a file input element before that element and click on it and then remove it once you select the file and change event is fired.

**Comment by KhodeN** [comment]
Yes. But when user clicks  on <div ng-file-select> the click event triggered on new <input type=file> and the window for select files shows. It's ok for real user, but for selenium (webdriver) tests the window blocks tests: test is expecting for user answer (selecting file).

P.S. My English is terrible, I know this)

**Comment by joshribakoff** [comment]
> But when user clicks on <div ng-file-select> the click event triggered on new <input type=file> and the window for select files shows. 

In Selenium we're not to click on the file input. You "send keys" to the file input, which bypasses the file selection dialog altogether. Selenium is sending keys to the element that is visible that matched my selector. Even if the element is replaced, Selenium is interacting with the same replacement element that the real user is. So it would make sense to me that the issue is with "sending keys" to an input rather than clicking it. Its not likely that the issue is Selenium interacting with the wrong element.

**Comment by danialfarid** [comment]
Since version 3.3.0 the underlying input file element will not be removed after the change event. That might fix the selenium problem, could you verify?

**Comment by KhodeN** [comment]
OK, today or tomorrow I'd check

**Comment by KhodeN** [comment]
No
1. need to remove input element on scope $destroy
2. need to input element already existed before starting the test
3. alternatively you can listen some custom DOM event for call `createFileInput` to create just input without click on it. Thus test will can to create element to use it.

**Comment by sirkkalap** [comment]
@danialfarid do I read you correctly at Apr 14, that you suggest we:

1. use selenium to click the ngf-select button
2. Wait for the dialog to dismiss
3. use selenium "send keys" to type into the "not removed" "input type=file"
4. submit somehow the upload

I have trouble implementing 2 and 4.

-Pete

**Comment by danialfarid** [comment]
Please follow this thread: https://github.com/danialfarid/ng-file-upload/issues/710#issuecomment-103545695
The change listener is registered after you click on the button, so you need to click first and then send key to the input with the same id.

**Comment by danialfarid** [comment]
since version 5.0.0 you can set `ngf-reset-on-click` to false for testing

**Comment by KhodeN** [comment]
thx

**Comment by danialfarid** [comment]
Since version 7 there won't be a new element created on each click so that would make the e2e testing easier.

**Comment by kbangur** [comment]
This thread went to a lot of discussions and I am finding it difficult to summarize! So can someone please help me understand what the problem was altogether? And also, how the solution was achieved? I am testing a similar AngularJS custom directive using Sahi web driver. The approach was very similar to that of Selenium where in Sahi proxy would 'inject' the file to be uploaded into the Http request against the file input element and can be submitted as usual. But the same is not working in my case only when I was testing an AngularJS file upload component.

**Comment by sirkkalap** [comment]
My workaround was to find the hidden file-upload input and inject javascript to unhide it before using Selenium Webdriver .type() function to enter the upload filename to the field. I am unsure about any other working solutions.

**Comment by adrielnancy224** [comment]
@danialfarid https://javascripter.space/questions/add-html-content-to-an-element-within-a-directive-and-create-a-custom-function-to-manipulate-it-locally
