### ISSUE TITLE
hint.css tooltips not working with ng-file-select in IE8

### ISSUE THREAD

**Issue by BannedForLife** [danialfarid/ng-file-upload#664]
When I attach ng-file-select to an icon/button it loses the tool tip on hover. The tool tip is still activated by hovering on the parent element but as soon as I hover over the ng-file-select element it disappears.

**Comment by BannedForLife** [comment]
It's not just hint.css I have tried angular-ui-bootstrap and the tool tips for that did not work either.

**Comment by danialfarid** [comment]
That's because a flash object element will be placed over the element when you hover over that element to be able to upload using flash. That feature could be added to FileAPI to copy the tooltip of the original element on the flash. You can create a ticket on FileAPI github https://github.com/mailru/FileAPI and link it here so if that's implemented I could add it here too.

**Comment by BannedForLife** [comment]
Will do. Thanks.

**Comment by BannedForLife** [comment]
They said they wont do it so I guess that's that. Thanks for the information anyway.

**Comment by danialfarid** [comment]
Could you link that issue that you opened on FileAPI here.
