### ISSUE TITLE
iPhone 6+ safari crashing.

### ISSUE THREAD

**Issue by dragonfire1119** [danialfarid/ng-file-upload#667]
```
<div class="btn btn-block btn-primary" 
                 ng-file-select 
                 ng-model="files"
                 ng-hide="toMany"
                 ng-capture="camera"
                 accept="image/*"><span class="glyphicon glyphicon-camera"></span> Upload photos</div>
```
When I click take photo then I say use this pic. It reloads the page and says "A problem occurred with this webpage so it was reloaded.". The camera capture seems to crash on upload It hasn't crashed on Google Chrome though only on safari.

This doesn't work on the demo page either.

If I remove all the tabs it seems to work. If I have allot of tabs open the browser crashes. I'm thinking it might be a memory issue.

**Comment by GLoganDR** [comment]
I also have this problem. Even with few tabs open and resizing the photos, it still fails... any answer or solution so far? We have tried a variety of things.

**Comment by danialfarid** [comment]
Does the demo page work?

**Comment by GLoganDR** [comment]
I'm seeing this problem on a lot of reports on Stack Overflow and other places about if you use the actual iPhone camera, it crashes Safari as you take pictures. I'm pretty sure this might be a Safari memory issue like dragonfire said. 

I have an issue up with Apple about it. I only see it happening on Safari and not Chrome or Firefox. It's very frustrating, because that's a lot of customers we can't support with mobile Safari, and instead, we have to make them take photos with the phone and come back to the site to upload them... It doesn't appear to be working on the demo page.

**Comment by austinpray** [comment]
Yep. Seeing this on iOS 8.4. Going to try to get a plunkr or something up to demonstrate.

**Comment by austinpray** [comment]
Alright friends. So I was able to narrow it down to this: https://github.com/danialfarid/ng-file-upload/blob/a5a55eb4afc41d6d2710593da75a71f9f7de0630/demo/src/main/webapp/js/upload.js#L18-L28

Do __not__ watch the files scope object on mobile safari. You will run out of memory really really quick.

Use `ngf-change="upload($files)"` instead.

**Comment by gcarling** [comment]
I'm seeing this issue as well. I just tried doing what @austinpray suggested - the issue itself was inconsistent to reproduce before but it seems like making this change has helped the issue but not completely fixed it, i.e. we see it less often but still once in a while.

**Comment by danialfarid** [comment]
@gcarling Do you have many `ngf-src` or `ngf-thumbnail` in your page?
Those are also watching the model for changes so that could cause this behaviour too.

**Comment by shawnzam** [comment]
@austinpray Can you kindly elaborate on this solution? Perhaps even a new forked repo?
