### ISSUE TITLE
Android ngf-capture="camera"

### ISSUE THREAD

**Issue by kylehind** [danialfarid/ng-file-upload#828]
Hi
I've ensured my app has the correct permissions available but can only access files not the camera on Android phones, 
Working fine with iOS
Thanks, Kyle

**Comment by jviqueira** [comment]
I have the same problem

**Comment by romaderi** [comment]
any news on this issue ?

**Comment by danialfarid** [comment]
What versoin of android?  it might be a known issue.
The plugin just adds capture="camera" to the input element, nothing fancy happening here to cause the issue unless the browser doesn't support it properly.

**Comment by apmitchell** [comment]
I'm having this same issue I believe. I have ngf-capture="true" and have tried ngf-capture="camera", but am not able to access the camera on android devices

**Comment by lpsBetty** [comment]
I think I know the reason:

Since Android 6.0, the Android permissions checking mechanism has been changed. In the past, the permissions were granted by users when they decide to install the app. Now, the permissions should be granted by a user when he/she is using the app.

see: https://github.com/NeoLSN/cordova-plugin-android-permission

**Comment by lpsBetty** [comment]
Also related to this issue: https://github.com/danialfarid/ng-file-upload/issues/1696#issuecomment-271700171
