### ISSUE TITLE
Ngf-select breaks table layout (Chrome)

### ISSUE THREAD

**Issue by rwee** [danialfarid/ng-file-upload#949]
Hi, great plugin.

I noticed ngf-select is breaking my CSS table layout. I didn't see any breaking styles in the directive CSS.

The issue is in Chrome (Ubuntu). When the ngf-select is showing, the layout collapses (the footer is no longer at the bottom of the browser window).

Any idea what might be causing this? Replicable: 
http://jsfiddle.net/nvrh9hca/

**Comment by danialfarid** [comment]
It is because if you use an element other than input type file it will add an invisible input type file at the end of body. Seems like adding any element after the footer in your example cause this to happen.
You could fix your css accordingly to handle another element after footer, or you could use input type file instead of div for the ngf-select.

**Comment by rwee** [comment]
That was it, I didn't catch that input being added. Thanks for the information, I switched to using an opacity:0 input within a drop-box styled div.
