### ISSUE TITLE
Specify excluded patterns

### ISSUE THREAD

**Issue by hardvain** [danialfarid/ng-file-upload#991]
Is there a way by which I can specify patterns that should be excluded from the choose file pop up? At present we can give an accept pattern to allow choosing of only those files matching the accept pattern. Do we have the ability to specify patterns that should be excluded and allow everything else?

**Comment by danialfarid** [comment]
No
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input

accept
If the value of the type attribute is file, this attribute indicates the types of files that the server accepts; otherwise it is ignored. The value must be a comma-separated list of unique content type specifiers:
A file extension starting with the STOP character (U+002E). (E.g.: ".jpg,.png,.doc")
A valid MIME type with no extensions
audio/* representing sound files HTML5
video/* representing video files HTML5
image/* representing image files HTML5
